require('options')

-- Setup
require('setup.bufferline')
require('setup.comment')
require('setup.colorizer')
require('setup.dashboard')
require('setup.gitsigns')
require('setup.compe')
require('setup.autopairs')
require('setup.toggleterm')
require('setup.tree')
require('setup.treesitter')
require('setup.trouble')
require('setup.telescope')
require('setup.blankline')
require('setup.signature')
-- require('setup.nonicons')
-- require('setup.snips')
require('luasnip/loaders/from_vscode').lazy_load()
require('setup.lspconfig')
require('lspicon')
-- require('setup.spell')

require('languages.emmet')
require('languages.efm')

require('statusline')
require('highlights')
require('mappings')
require('autocommands')
