require("nvim-navic").setup({
    icons = {
        Namespace = " ",
        Package = " ",
        String = " ",
        Number = " ",
        Boolean = "◩ ",
        Array = " ",
        Object = " ",
        Key = " ",
        Null = "ﳠ ",

        Class = " (class)",
        Constant = " (constant)",
        Constructor = " (constructor)",
        Enum = " (enum)",
        EnumMember = " (enum member)",
        Event = " (event)",
        Field = " (field)",
        File = " (file)",
        Folder = " (folder)",
        Function = " (function)",
        Interface = " (interface)",
        Keyword = " (keyword)",
        Method = " (method)",
        Module = "{} (module)",
        Operator = " (operator)",
        Property = " (property)",
        Reference = " (reference)",
        Snippet = " (snippet)",
        Struct = " (enum)",
        Text = " (text)",
        TypeParameter = " (type parameter)",
        Unit = " (unit)",
        Value = " (value)",
        Variable = " (variable)",
    },
    highlight = false,
    separator = " > ",
    depth_limit = 0,
    depth_limit_indicator = "..",
})
